server:
  port: 8400

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    database: 2
  cache:
    redis:
      time-to-live: ${CACHE_REDIS_TIME_TO_LIVE:60S}

logging:
  level:
    com.dc3: DEBUG
    #com.dc3.center.manager.service.rabbit: INFO
  file:
    name: dc3/logs/center/${spring.application.name}.log
