driver:
  name: MqttDriver
  description: @project.description@
  schedule:
    status:
      enable: true
      corn: '0/10 * * * * ?'
    read:
      enable: false
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn:  '0/5 * * * * ?'
  point-attribute:
    - displayName: 指令Topic
      name: commandTopic
      type: string
      value: commandTopic
      description: 测点/设备接收下行指令的Mqtt主题
    - displayName: 指令Qos
      name: commandQos
      type: int
      value: 2
      description: 测点/设备接收下行指令的Mqtt主题的Qos
  mqtt:
    username: dc3
    password: dc3
    url: tcp://dc3-rabbitmq:1883
    #也可以连接到其他的mqtt服务器，例如：emqx，你可以在docker-compose.yml中找到，并启动它
    #url: tcp://dc3-emqx:1884
    qos:
      - 0
    topics:
      - mqtt/group/device/#
    client:
      id: dc3-mqtt-client
    default:
      topic: dc3-mqtt-topic
      qos: 1
      receive:
        enable: true
    keep-alive: 5
    completion-timeout: 3000

server:
  port: 8701

spring:
  application:
    name: @project.artifactId@

logging:
  level:
    com.dc3.common.sdk: DEBUG
    com.dc3: DEBUG
  file:
    name: dc3/logs/driver/mqtt/${spring.application.name}.log